### ISSUE TITLE
create 'music' module pages/layouts/components - daft.fm build

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-ui-nuxt#87]
Design refs: 

- https://github.com/serpcompany/serp-nuxt-template/wiki/Modules#music
- https://serp-theme-ruhul.netlify.app/archive/archive_v1

---

- [ ] Home

## collections

- [ ] /artists/
- [ ] /albums/
- [ ] /songs/
- [ ] /glossary/

```
# do later

/samples/
/genres/
/people/
/podcasts/
/gear/
/moods/
/events/
/venues/
/lyrics/
```

## singles (multipage)

- [ ] serpcompany/daft.fm2#1
- [ ] serpcompany/daft.fm2#2
- [ ] serpcompany/daft.fm2#3
- [ ] /glossary/[term]/
- [ ] /sample/[sampleId]/[artistA]-[song]-[artistB]-[song]/

```
# do later

/person/[person]-[dbId]/
/genre/[genre]-[dbId]/
/venue/[venue]-[dbId]/
/event/[event]-[dbId]/
/podcast/[podcast]-[dbId]/
```

## old notes

- [ ] artists/[artist] - multipage (overview) w/ a text area, stats sidebar and a section for each thing below (a table of songs, a grid of album covers, and a tag cloud / link hub) its like a mini index page
- [ ] artists/[artist]#songs - table of songs in rows - [reference](https://www.last.fm/music/Daft+Punk/+tracks), [reference](https://www.last.fm/tag/experimental/tracks#:~:text=Shouts-,Experimental%20Tracks,-Rank)
- [ ] artists/albums - multipage (grid of squares) - [reference](https://www.last.fm/music/Daft+Punk/+albums?order=most_popular), [reference](https://www.last.fm/tag/experimental/albums#:~:text=Shouts-,Experimental%20Albums,-Eternal%20Grey)
- [ ] artists/images - multipage (grid of squares) - [reference](https://www.last.fm/music/Daft+Punk/+images)

## Multipage (double header)

The multipage header would still be here, only showing the top level `Artist Headings`.

There will either be a subheader focusing on the single thing, or we could just add that single thing to the main header after artist name. 

`Daft Punk` on artist page would become `Daft Punk - Get Lucky` on the single song page, and `Daft Punk - Discovery` on the single album page.

If we can think of multiple tabs needed for these artist + [single] pages then we could add them later but better to start without

- [ ] artists/songs/[song] - multipage (of artist) but add a subheader for the song h1, and just go one step further down the breadcrum chain. has description, lyrics, video / lyric video / short video, credits
- [ ] artists/albums/[album] - multipage (of artist) but add a subheader for the album h1, and just go one step further down the breadcrum chain. has description, release stats, credits, tracklist (songs table)
